[2023-08-23T02:34:51.136+0000] {processor.py:157} INFO - Started process (PID=11306) to work on /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:34:51.137+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/04_python_operator_with_decorator.py for tasks to queue
[2023-08-23T02:34:51.138+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:34:51.138+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:34:51.158+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:34:51.147+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/04_python_operator_with_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/04_python_operator_with_decorator.py", line 18, in <module>
    print_context_task = print_context("@task로 python task를 실행해보자!")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 345, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 54, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 212, in __init__
    super().__init__(task_id=task_id, **kwargs_to_upstream, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-08-23T02:34:51.159+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:34:51.188+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/04_python_operator_with_decorator.py took 0.056 seconds
[2023-08-23T02:35:21.869+0000] {processor.py:157} INFO - Started process (PID=11363) to work on /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:35:21.870+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/04_python_operator_with_decorator.py for tasks to queue
[2023-08-23T02:35:21.870+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:35:21.870+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:35:21.880+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:35:21.876+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/04_python_operator_with_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/04_python_operator_with_decorator.py", line 18, in <module>
    print_context_task = print_context("@task로 python task를 실행해보자!")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 345, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 54, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 212, in __init__
    super().__init__(task_id=task_id, **kwargs_to_upstream, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-08-23T02:35:21.881+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:35:21.908+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/04_python_operator_with_decorator.py took 0.041 seconds
[2023-08-23T02:35:51.965+0000] {processor.py:157} INFO - Started process (PID=11420) to work on /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:35:51.966+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/04_python_operator_with_decorator.py for tasks to queue
[2023-08-23T02:35:51.967+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:35:51.967+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:35:51.974+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:35:51.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/04_python_operator_with_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/04_python_operator_with_decorator.py", line 18, in <module>
    print_context_task = print_context("@task로 python task를 실행해보자!")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 345, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 54, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 212, in __init__
    super().__init__(task_id=task_id, **kwargs_to_upstream, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-08-23T02:35:51.975+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:35:51.996+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/04_python_operator_with_decorator.py took 0.034 seconds
[2023-08-23T02:36:22.530+0000] {processor.py:157} INFO - Started process (PID=11477) to work on /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:22.531+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/04_python_operator_with_decorator.py for tasks to queue
[2023-08-23T02:36:22.532+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:22.532+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:22.543+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:22.539+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/04_python_operator_with_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/04_python_operator_with_decorator.py", line 18, in <module>
    print_context_task = print_context("@task로 python task를 실행해보자!")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 345, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 54, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 212, in __init__
    super().__init__(task_id=task_id, **kwargs_to_upstream, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-08-23T02:36:22.544+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:22.575+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/04_python_operator_with_decorator.py took 0.049 seconds
[2023-08-23T02:36:53.423+0000] {processor.py:157} INFO - Started process (PID=11534) to work on /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:53.425+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/04_python_operator_with_decorator.py for tasks to queue
[2023-08-23T02:36:53.426+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:53.425+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:53.435+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:53.433+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/04_python_operator_with_decorator.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/04_python_operator_with_decorator.py", line 18, in <module>
    print_context_task = print_context("@task로 python task를 실행해보자!")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 345, in __call__
    **self.kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/python.py", line 54, in __init__
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 212, in __init__
    super().__init__(task_id=task_id, **kwargs_to_upstream, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 166, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 799, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key '' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2023-08-23T02:36:53.435+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:53.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/04_python_operator_with_decorator.py took 0.038 seconds
[2023-08-23T02:36:57.767+0000] {processor.py:157} INFO - Started process (PID=11540) to work on /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:57.768+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/04_python_operator_with_decorator.py for tasks to queue
[2023-08-23T02:36:57.770+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:57.769+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:57.784+0000] {processor.py:836} INFO - DAG(s) dict_keys(['04_python_operator_with_decorator']) retrieved from /opt/airflow/dags/04_python_operator_with_decorator.py
[2023-08-23T02:36:57.936+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:57.936+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:04_python_operator_with_decorator
[2023-08-23T02:36:57.954+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:57.954+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:04_python_operator_with_decorator
[2023-08-23T02:36:57.970+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:57.970+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:04_python_operator_with_decorator
[2023-08-23T02:36:57.997+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:57.997+0000] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-23T02:36:58.018+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:58.018+0000] {dag.py:2763} INFO - Creating ORM DAG for 04_python_operator_with_decorator
[2023-08-23T02:36:58.043+0000] {logging_mixin.py:150} INFO - [2023-08-23T02:36:58.042+0000] {dag.py:3508} INFO - Setting next_dagrun for 04_python_operator_with_decorator to 2023-08-30T15:00:00+00:00, run_after=2023-09-29T15:00:00+00:00
[2023-08-23T02:36:58.077+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/04_python_operator_with_decorator.py took 0.315 seconds
