[2023-08-24T02:48:11.414+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [queued]>
[2023-08-24T02:48:11.427+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [queued]>
[2023-08-24T02:48:11.427+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-08-24T02:48:11.450+0000] {taskinstance.py:1327} INFO - Executing <Task(SeoulApiToCsvOperator): num_corona> on 2023-08-24 02:47:32.557530+00:00
[2023-08-24T02:48:11.458+0000] {standard_task_runner.py:57} INFO - Started process 4191 to run task
[2023-08-24T02:48:11.462+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '16_base_operator', 'num_corona', 'manual__2023-08-24T02:47:32.557530+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/16_base_operator.py', '--cfg-path', '/tmp/tmpx30utf1b']
[2023-08-24T02:48:11.463+0000] {standard_task_runner.py:85} INFO - Job 200: Subtask num_corona
[2023-08-24T02:48:11.520+0000] {task_command.py:410} INFO - Running <TaskInstance: 16_base_operator.num_corona manual__2023-08-24T02:47:32.557530+00:00 [running]> on host 05c492c53b17
[2023-08-24T02:48:11.637+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='16_base_operator' AIRFLOW_CTX_TASK_ID='num_corona' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T02:47:32.557530+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T02:47:32.557530+00:00'
[2023-08-24T02:48:11.649+0000] {base.py:73} INFO - Using connection ID 'openapi.seoul.go.kr' for task execution.
[2023-08-24T02:48:11.649+0000] {logging_mixin.py:150} INFO - openapi.seoul.go.kr
[2023-08-24T02:48:11.655+0000] {seoul_api_to_csv_operator.py:36} INFO - 시작: 1
[2023-08-24T02:48:11.656+0000] {seoul_api_to_csv_operator.py:37} INFO - 끝: 1000
[2023-08-24T02:48:11.844+0000] {seoul_api_to_csv_operator.py:36} INFO - 시작: 1001
[2023-08-24T02:48:11.845+0000] {seoul_api_to_csv_operator.py:37} INFO - 끝: 2000
[2023-08-24T02:48:11.966+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/seoul_api_to_csv_operator.py", line 47, in execute
    if not os.path.exsits(self.file_path):
AttributeError: module 'posixpath' has no attribute 'exsits'
[2023-08-24T02:48:11.976+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=16_base_operator, task_id=num_corona, execution_date=20230824T024732, start_date=20230824T024811, end_date=20230824T024811
[2023-08-24T02:48:11.993+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 200 for task num_corona (module 'posixpath' has no attribute 'exsits'; 4191)
[2023-08-24T02:48:12.037+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-24T02:48:12.079+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
