[2023-08-20T22:43:34.970+0000] {processor.py:157} INFO - Started process (PID=55) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:43:34.971+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:43:34.973+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:43:34.972+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:43:35.005+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:43:35.002+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:43:35.006+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:43:35.025+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.059 seconds
[2023-08-20T22:44:05.686+0000] {processor.py:157} INFO - Started process (PID=152) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:44:05.687+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:44:05.688+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:44:05.688+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:44:05.712+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:44:05.710+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:44:05.712+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:44:05.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.042 seconds
[2023-08-20T22:44:36.182+0000] {processor.py:157} INFO - Started process (PID=243) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:44:36.183+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:44:36.184+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:44:36.184+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:44:36.207+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:44:36.206+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:44:36.208+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:44:36.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.043 seconds
[2023-08-20T22:45:06.559+0000] {processor.py:157} INFO - Started process (PID=334) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:45:06.560+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:45:06.561+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:45:06.561+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:45:06.585+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:45:06.584+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:45:06.586+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:45:06.603+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.047 seconds
[2023-08-20T22:45:37.025+0000] {processor.py:157} INFO - Started process (PID=425) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:45:37.026+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:45:37.027+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:45:37.027+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:45:37.048+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:45:37.046+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:45:37.048+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:45:37.062+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T22:46:07.482+0000] {processor.py:157} INFO - Started process (PID=516) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:46:07.484+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:46:07.486+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:46:07.485+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:46:07.525+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:46:07.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:46:07.526+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:46:07.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.067 seconds
[2023-08-20T22:46:38.466+0000] {processor.py:157} INFO - Started process (PID=607) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:46:38.467+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:46:38.468+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:46:38.467+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:46:38.486+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:46:38.485+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:46:38.487+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:46:38.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T22:47:09.316+0000] {processor.py:157} INFO - Started process (PID=698) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:47:09.316+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:47:09.317+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:47:09.317+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:47:09.336+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:47:09.335+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:47:09.336+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:47:09.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.035 seconds
[2023-08-20T22:47:39.640+0000] {processor.py:157} INFO - Started process (PID=789) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:47:39.641+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:47:39.642+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:47:39.642+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:47:39.662+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:47:39.661+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:47:39.663+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:47:39.675+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T22:48:10.297+0000] {processor.py:157} INFO - Started process (PID=880) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:48:10.298+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:48:10.298+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:48:10.298+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:48:10.322+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:48:10.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:48:10.323+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:48:10.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.045 seconds
[2023-08-20T22:48:41.140+0000] {processor.py:157} INFO - Started process (PID=971) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:48:41.140+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:48:41.141+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:48:41.141+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:48:41.160+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:48:41.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:48:41.161+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:48:41.174+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T22:49:11.605+0000] {processor.py:157} INFO - Started process (PID=1063) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:49:11.607+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:49:11.609+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:49:11.609+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:49:11.642+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:49:11.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:49:11.642+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:49:11.664+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.067 seconds
[2023-08-20T22:49:42.086+0000] {processor.py:157} INFO - Started process (PID=1154) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:49:42.088+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:49:42.088+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:49:42.088+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:49:42.107+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:49:42.106+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:49:42.108+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:49:42.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T22:50:13.094+0000] {processor.py:157} INFO - Started process (PID=1245) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:50:13.095+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:50:13.097+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:50:13.096+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:50:13.116+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:50:13.115+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:50:13.116+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:50:13.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T22:50:43.967+0000] {processor.py:157} INFO - Started process (PID=1336) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:50:43.969+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:50:43.970+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:50:43.970+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:50:44.001+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:50:43.999+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:50:44.002+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:50:44.023+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.060 seconds
[2023-08-20T22:51:14.939+0000] {processor.py:157} INFO - Started process (PID=1427) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:51:14.940+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:51:14.940+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:51:14.940+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:51:14.961+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:51:14.960+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:51:14.961+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:51:14.974+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T22:51:45.824+0000] {processor.py:157} INFO - Started process (PID=1518) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:51:45.825+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:51:45.826+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:51:45.826+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:51:45.850+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:51:45.849+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:51:45.851+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:51:45.863+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.042 seconds
[2023-08-20T22:52:16.590+0000] {processor.py:157} INFO - Started process (PID=1610) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:52:16.591+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:52:16.592+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:52:16.592+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:52:16.613+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:52:16.612+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:52:16.614+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:52:16.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.043 seconds
[2023-08-20T22:52:46.921+0000] {processor.py:157} INFO - Started process (PID=1701) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:52:46.922+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:52:46.924+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:52:46.923+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:52:47.001+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:52:47.000+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:52:47.001+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:52:47.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.101 seconds
[2023-08-20T22:53:17.106+0000] {processor.py:157} INFO - Started process (PID=1792) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:53:17.108+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:53:17.108+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:53:17.108+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:53:17.128+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:53:17.127+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:53:17.128+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:53:17.141+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T22:53:47.949+0000] {processor.py:157} INFO - Started process (PID=1883) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:53:47.951+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:53:47.952+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:53:47.951+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:53:47.971+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:53:47.969+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:53:47.971+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:53:47.985+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T22:54:18.606+0000] {processor.py:157} INFO - Started process (PID=1974) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:54:18.607+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:54:18.608+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:54:18.608+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:54:18.626+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:54:18.625+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:54:18.627+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:54:18.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T22:54:49.472+0000] {processor.py:157} INFO - Started process (PID=2065) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:54:49.473+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:54:49.474+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:54:49.474+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:54:49.493+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:54:49.492+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:54:49.493+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:54:49.507+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T22:55:20.197+0000] {processor.py:157} INFO - Started process (PID=2156) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:55:20.198+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:55:20.199+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:55:20.199+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:55:20.217+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:55:20.216+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:55:20.218+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:55:20.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.035 seconds
[2023-08-20T22:55:50.371+0000] {processor.py:157} INFO - Started process (PID=2247) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:55:50.372+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:55:50.373+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:55:50.372+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:55:50.393+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:55:50.391+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:55:50.393+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:55:50.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T22:56:20.826+0000] {processor.py:157} INFO - Started process (PID=2339) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:56:20.827+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:56:20.828+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:56:20.828+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:56:20.846+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:56:20.845+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:56:20.846+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:56:20.859+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T22:56:51.446+0000] {processor.py:157} INFO - Started process (PID=2430) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:56:51.447+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:56:51.448+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:56:51.448+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:56:51.467+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:56:51.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:56:51.468+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:56:51.480+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T22:57:21.962+0000] {processor.py:157} INFO - Started process (PID=2521) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:57:21.963+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:57:21.964+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:57:21.964+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:57:21.990+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:57:21.987+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:57:21.990+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:57:22.008+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.049 seconds
[2023-08-20T22:57:52.728+0000] {processor.py:157} INFO - Started process (PID=2613) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:57:52.730+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:57:52.730+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:57:52.730+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:57:52.753+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:57:52.752+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:57:52.754+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:57:52.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.045 seconds
[2023-08-20T22:58:22.864+0000] {processor.py:157} INFO - Started process (PID=2704) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:58:22.865+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:58:22.866+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:58:22.866+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:58:22.889+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:58:22.887+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:58:22.889+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:58:22.904+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.043 seconds
[2023-08-20T22:58:53.775+0000] {processor.py:157} INFO - Started process (PID=2802) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:58:53.776+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:58:53.777+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:58:53.777+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:58:53.797+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:58:53.796+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:58:53.797+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:58:53.812+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T22:59:24.561+0000] {processor.py:157} INFO - Started process (PID=2893) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:59:24.563+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:59:24.564+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:59:24.564+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:59:24.583+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:59:24.582+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:59:24.583+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:59:24.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T22:59:54.771+0000] {processor.py:157} INFO - Started process (PID=2983) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:59:54.773+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T22:59:54.774+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:59:54.773+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:59:54.795+0000] {logging_mixin.py:150} INFO - [2023-08-20T22:59:54.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T22:59:54.796+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T22:59:54.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:00:25.648+0000] {processor.py:157} INFO - Started process (PID=3075) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:00:25.649+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:00:25.651+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:00:25.650+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:00:25.672+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:00:25.671+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:00:25.672+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:00:25.685+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:00:56.621+0000] {processor.py:157} INFO - Started process (PID=3166) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:00:56.622+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:00:56.623+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:00:56.623+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:00:56.769+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:00:56.768+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:00:56.770+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:00:56.781+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.163 seconds
[2023-08-20T23:01:26.831+0000] {processor.py:157} INFO - Started process (PID=3258) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:01:26.833+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:01:26.834+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:01:26.833+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:01:26.857+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:01:26.856+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:01:26.858+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:01:26.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.045 seconds
[2023-08-20T23:01:57.047+0000] {processor.py:157} INFO - Started process (PID=3349) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:01:57.048+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:01:57.048+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:01:57.048+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:01:57.067+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:01:57.066+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:01:57.067+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:01:57.079+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.035 seconds
[2023-08-20T23:02:27.998+0000] {processor.py:157} INFO - Started process (PID=3440) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:02:27.999+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:02:28.000+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:02:28.000+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:02:28.019+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:02:28.018+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:02:28.019+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:02:28.032+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:02:58.923+0000] {processor.py:157} INFO - Started process (PID=3531) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:02:58.924+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:02:58.925+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:02:58.925+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:02:58.944+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:02:58.943+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:02:58.944+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:02:58.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:03:29.848+0000] {processor.py:157} INFO - Started process (PID=3622) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:03:29.850+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:03:29.850+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:03:29.850+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:03:29.870+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:03:29.869+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:03:29.870+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:03:29.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:04:00.649+0000] {processor.py:157} INFO - Started process (PID=3713) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:04:00.650+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:04:00.651+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:04:00.651+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:04:00.671+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:04:00.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:04:00.671+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:04:00.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:04:30.941+0000] {processor.py:157} INFO - Started process (PID=3804) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:04:30.943+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:04:30.944+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:04:30.943+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:04:30.964+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:04:30.963+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:04:30.965+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:04:30.979+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:05:01.653+0000] {processor.py:157} INFO - Started process (PID=3895) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:05:01.654+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:05:01.655+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:05:01.655+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:05:01.680+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:05:01.679+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:05:01.681+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:05:01.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.049 seconds
[2023-08-20T23:05:32.413+0000] {processor.py:157} INFO - Started process (PID=3986) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:05:32.414+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:05:32.415+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:05:32.415+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:05:32.435+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:05:32.434+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:05:32.435+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:05:32.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:06:03.395+0000] {processor.py:157} INFO - Started process (PID=4078) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:06:03.396+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:06:03.397+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:06:03.397+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:06:03.416+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:06:03.415+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:06:03.416+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:06:03.428+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:06:33.702+0000] {processor.py:157} INFO - Started process (PID=4169) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:06:33.703+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:06:33.703+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:06:33.703+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:06:33.722+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:06:33.721+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:06:33.722+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:06:33.735+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:07:03.933+0000] {processor.py:157} INFO - Started process (PID=4260) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:07:03.935+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:07:03.936+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:07:03.935+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:07:03.955+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:07:03.954+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:07:03.955+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:07:03.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:07:34.639+0000] {processor.py:157} INFO - Started process (PID=4351) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:07:34.640+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:07:34.641+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:07:34.640+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:07:34.659+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:07:34.658+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:07:34.660+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:07:34.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:08:05.582+0000] {processor.py:157} INFO - Started process (PID=4442) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:08:05.583+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:08:05.583+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:08:05.583+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:08:05.602+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:08:05.601+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:08:05.602+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:08:05.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.034 seconds
[2023-08-20T23:08:36.124+0000] {processor.py:157} INFO - Started process (PID=4533) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:08:36.125+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:08:36.126+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:08:36.126+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:08:36.145+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:08:36.144+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:08:36.145+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:08:36.159+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:09:06.504+0000] {processor.py:157} INFO - Started process (PID=4624) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:09:06.506+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:09:06.507+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:09:06.507+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:09:06.526+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:09:06.524+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:09:06.527+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:09:06.539+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:18:28.293+0000] {processor.py:157} INFO - Started process (PID=4723) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:18:28.294+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:18:28.296+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:18:28.295+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:18:28.325+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:18:28.324+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:18:28.326+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:18:28.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.056 seconds
[2023-08-20T23:18:59.109+0000] {processor.py:157} INFO - Started process (PID=4814) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:18:59.110+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:18:59.111+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:18:59.111+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:18:59.132+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:18:59.131+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:18:59.133+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:18:59.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:19:29.899+0000] {processor.py:157} INFO - Started process (PID=4905) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:19:29.900+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:19:29.901+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:19:29.901+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:19:29.922+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:19:29.921+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:19:29.923+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:19:29.940+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.044 seconds
[2023-08-20T23:20:00.853+0000] {processor.py:157} INFO - Started process (PID=4996) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:20:00.854+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:20:00.855+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:20:00.855+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:20:00.876+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:20:00.875+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:20:00.877+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:20:00.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.041 seconds
[2023-08-20T23:20:31.609+0000] {processor.py:157} INFO - Started process (PID=5087) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:20:31.610+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:20:31.611+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:20:31.611+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:20:31.635+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:20:31.633+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:20:31.635+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:20:31.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.045 seconds
[2023-08-20T23:21:02.170+0000] {processor.py:157} INFO - Started process (PID=5178) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:21:02.171+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:21:02.172+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:21:02.172+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:21:02.197+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:21:02.196+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:21:02.198+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:21:02.213+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.046 seconds
[2023-08-20T23:21:33.031+0000] {processor.py:157} INFO - Started process (PID=5269) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:21:33.032+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:21:33.033+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:21:33.033+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:21:33.054+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:21:33.053+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:21:33.054+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:21:33.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:22:03.179+0000] {processor.py:157} INFO - Started process (PID=5360) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:22:03.180+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:22:03.181+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:22:03.181+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:22:03.207+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:22:03.205+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:22:03.207+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:22:03.223+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.047 seconds
[2023-08-20T23:22:33.651+0000] {processor.py:157} INFO - Started process (PID=5451) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:22:33.652+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:22:33.653+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:22:33.653+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:22:33.676+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:22:33.675+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:22:33.677+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:22:33.694+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.046 seconds
[2023-08-20T23:23:04.171+0000] {processor.py:157} INFO - Started process (PID=5542) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:23:04.173+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:23:04.173+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:23:04.173+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:23:04.194+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:23:04.193+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:23:04.194+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:23:04.207+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:23:34.587+0000] {processor.py:157} INFO - Started process (PID=5633) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:23:34.587+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:23:34.588+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:23:34.588+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:23:34.607+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:23:34.606+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:23:34.607+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:23:34.619+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.035 seconds
[2023-08-20T23:24:05.266+0000] {processor.py:157} INFO - Started process (PID=5724) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:24:05.268+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:24:05.269+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:24:05.268+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:24:05.288+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:24:05.288+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:24:05.289+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:24:05.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:24:35.683+0000] {processor.py:157} INFO - Started process (PID=5815) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:24:35.685+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:24:35.686+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:24:35.685+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:24:35.710+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:24:35.709+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:24:35.711+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:24:35.730+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.051 seconds
[2023-08-20T23:25:06.282+0000] {processor.py:157} INFO - Started process (PID=5906) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:25:06.284+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:25:06.285+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:25:06.285+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:25:06.308+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:25:06.307+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:25:06.308+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:25:06.322+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.044 seconds
[2023-08-20T23:25:36.661+0000] {processor.py:157} INFO - Started process (PID=5997) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:25:36.662+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:25:36.663+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:25:36.663+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:25:36.685+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:25:36.684+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:25:36.685+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:25:36.698+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:26:06.879+0000] {processor.py:157} INFO - Started process (PID=6088) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:26:06.880+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:26:06.881+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:26:06.880+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:26:06.900+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:26:06.899+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:26:06.900+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:26:06.915+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:26:37.080+0000] {processor.py:157} INFO - Started process (PID=6179) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:26:37.081+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:26:37.082+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:26:37.082+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:26:37.103+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:26:37.102+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:26:37.103+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:26:37.117+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:27:07.523+0000] {processor.py:157} INFO - Started process (PID=6269) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:27:07.524+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:27:07.525+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:27:07.524+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:27:07.545+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:27:07.544+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:27:07.545+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:27:07.558+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:27:37.706+0000] {processor.py:157} INFO - Started process (PID=6359) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:27:37.708+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:27:37.708+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:27:37.708+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:27:37.728+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:27:37.727+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:27:37.728+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:27:37.743+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:28:08.884+0000] {processor.py:157} INFO - Started process (PID=6452) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:28:08.885+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:28:08.886+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:28:08.886+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:28:08.906+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:28:08.905+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:28:08.906+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:28:08.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:28:39.995+0000] {processor.py:157} INFO - Started process (PID=6544) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:28:39.995+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:28:39.996+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:28:39.996+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:28:40.017+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:28:40.016+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:28:40.017+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:28:40.031+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:29:10.601+0000] {processor.py:157} INFO - Started process (PID=6635) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:29:10.602+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:29:10.603+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:29:10.602+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:29:10.622+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:29:10.621+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:29:10.622+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:29:10.636+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:29:41.573+0000] {processor.py:157} INFO - Started process (PID=6726) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:29:41.575+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:29:41.576+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:29:41.575+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:29:41.601+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:29:41.600+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:29:41.602+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:29:41.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.048 seconds
[2023-08-20T23:30:11.861+0000] {processor.py:157} INFO - Started process (PID=6817) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:30:11.862+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:30:11.863+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:30:11.863+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:30:11.883+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:30:11.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:30:11.884+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:30:11.897+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:30:42.189+0000] {processor.py:157} INFO - Started process (PID=6908) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:30:42.190+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:30:42.190+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:30:42.190+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:30:42.216+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:30:42.215+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:30:42.217+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:30:42.230+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.044 seconds
[2023-08-20T23:31:12.422+0000] {processor.py:157} INFO - Started process (PID=6998) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:31:12.423+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:31:12.424+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:31:12.424+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:31:12.446+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:31:12.445+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:31:12.446+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:31:12.459+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.041 seconds
[2023-08-20T23:31:42.784+0000] {processor.py:157} INFO - Started process (PID=7089) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:31:42.785+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:31:42.786+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:31:42.786+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:31:42.806+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:31:42.805+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:31:42.806+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:31:42.819+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:32:13.128+0000] {processor.py:157} INFO - Started process (PID=7180) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:32:13.130+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:32:13.131+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:32:13.130+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:32:13.151+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:32:13.150+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:32:13.151+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:32:13.164+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:32:43.651+0000] {processor.py:157} INFO - Started process (PID=7272) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:32:43.652+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:32:43.653+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:32:43.653+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:32:43.673+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:32:43.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:32:43.674+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:32:43.687+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:33:14.280+0000] {processor.py:157} INFO - Started process (PID=7363) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:33:14.282+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:33:14.283+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:33:14.283+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:33:14.304+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:33:14.303+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:33:14.305+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:33:14.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:33:44.775+0000] {processor.py:157} INFO - Started process (PID=7454) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:33:44.776+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:33:44.777+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:33:44.777+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:33:44.797+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:33:44.796+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:33:44.797+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:33:44.811+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:34:15.683+0000] {processor.py:157} INFO - Started process (PID=7545) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:34:15.684+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:34:15.685+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:34:15.685+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:34:15.704+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:34:15.703+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:34:15.704+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:34:15.717+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:39:21.822+0000] {processor.py:157} INFO - Started process (PID=7636) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:39:21.823+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:39:21.824+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:39:21.824+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:39:21.851+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:39:21.849+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:39:21.852+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:39:21.868+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.050 seconds
[2023-08-20T23:39:52.682+0000] {processor.py:157} INFO - Started process (PID=7727) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:39:52.684+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:39:52.684+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:39:52.684+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:39:52.703+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:39:52.702+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:39:52.703+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:39:52.716+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:40:22.966+0000] {processor.py:157} INFO - Started process (PID=7818) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:40:22.967+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:40:22.967+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:40:22.967+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:40:22.990+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:40:22.988+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:40:22.990+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:40:23.003+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:40:53.315+0000] {processor.py:157} INFO - Started process (PID=7909) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:40:53.317+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:40:53.317+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:40:53.317+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:40:53.348+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:40:53.346+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:40:53.348+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:40:53.363+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.050 seconds
[2023-08-20T23:41:23.980+0000] {processor.py:157} INFO - Started process (PID=8000) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:41:23.981+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:41:23.982+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:41:23.982+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:41:24.000+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:41:23.999+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:41:24.001+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:41:24.014+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:41:54.182+0000] {processor.py:157} INFO - Started process (PID=8091) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:41:54.183+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:41:54.185+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:41:54.184+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:41:54.208+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:41:54.207+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:41:54.208+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:41:54.225+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.046 seconds
[2023-08-20T23:42:24.950+0000] {processor.py:157} INFO - Started process (PID=8183) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:42:24.951+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:42:24.952+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:42:24.952+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:42:24.977+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:42:24.976+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:42:24.978+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:42:24.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.047 seconds
[2023-08-20T23:42:55.721+0000] {processor.py:157} INFO - Started process (PID=8274) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:42:55.723+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:42:55.724+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:42:55.723+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:42:55.750+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:42:55.749+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:42:55.751+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:42:55.768+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.051 seconds
[2023-08-20T23:43:26.728+0000] {processor.py:157} INFO - Started process (PID=8365) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:43:26.730+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:43:26.731+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:43:26.731+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:43:26.754+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:43:26.753+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:43:26.755+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:43:26.768+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.042 seconds
[2023-08-20T23:43:57.058+0000] {processor.py:157} INFO - Started process (PID=8456) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:43:57.059+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:43:57.060+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:43:57.060+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:43:57.081+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:43:57.079+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:43:57.082+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:43:57.096+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:44:27.380+0000] {processor.py:157} INFO - Started process (PID=8547) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:44:27.381+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:44:27.383+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:44:27.382+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:44:27.412+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:44:27.410+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:44:27.413+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:44:27.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.054 seconds
[2023-08-20T23:44:57.949+0000] {processor.py:157} INFO - Started process (PID=8638) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:44:57.951+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:44:57.952+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:44:57.952+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:44:57.974+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:44:57.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:44:57.974+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:44:57.990+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.043 seconds
[2023-08-20T23:45:29.114+0000] {processor.py:157} INFO - Started process (PID=8729) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:45:29.115+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:45:29.116+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:45:29.116+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:45:29.137+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:45:29.136+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:45:29.137+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:45:29.151+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:45:59.628+0000] {processor.py:157} INFO - Started process (PID=8820) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:45:59.630+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:45:59.631+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:45:59.630+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:45:59.649+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:45:59.648+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:45:59.649+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:45:59.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:46:29.890+0000] {processor.py:157} INFO - Started process (PID=8911) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:46:29.892+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:46:29.893+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:46:29.893+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:46:29.915+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:46:29.914+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:46:29.916+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:46:29.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.041 seconds
[2023-08-20T23:47:00.514+0000] {processor.py:157} INFO - Started process (PID=9003) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:47:00.515+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:47:00.516+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:47:00.515+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:47:00.535+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:47:00.534+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:47:00.535+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:47:00.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:47:31.956+0000] {processor.py:157} INFO - Started process (PID=9094) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:47:31.959+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:47:31.961+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:47:31.960+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:47:31.986+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:47:31.985+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:47:31.987+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:47:32.004+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.052 seconds
[2023-08-20T23:48:02.983+0000] {processor.py:157} INFO - Started process (PID=9185) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:48:02.984+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:48:02.985+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:48:02.985+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:48:03.004+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:48:03.003+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:48:03.004+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:48:03.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.041 seconds
[2023-08-20T23:48:33.940+0000] {processor.py:157} INFO - Started process (PID=9276) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:48:33.941+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:48:33.942+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:48:33.942+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:48:33.968+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:48:33.965+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:48:33.968+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:48:33.983+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.046 seconds
[2023-08-20T23:49:04.936+0000] {processor.py:157} INFO - Started process (PID=9367) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:49:04.937+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:49:04.938+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:49:04.938+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:49:04.957+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:49:04.956+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:49:04.957+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:49:04.969+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.036 seconds
[2023-08-20T23:49:35.155+0000] {processor.py:157} INFO - Started process (PID=9458) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:49:35.156+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:49:35.157+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:49:35.157+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:49:35.177+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:49:35.176+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:49:35.178+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:49:35.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.042 seconds
[2023-08-20T23:50:05.857+0000] {processor.py:157} INFO - Started process (PID=9549) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:50:05.859+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:50:05.860+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:50:05.859+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:50:05.887+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:50:05.885+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:50:05.888+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:50:05.909+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.056 seconds
[2023-08-20T23:50:36.083+0000] {processor.py:157} INFO - Started process (PID=9639) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:50:36.083+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:50:36.084+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:50:36.084+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:50:36.105+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:50:36.104+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:50:36.106+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:50:36.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:51:06.733+0000] {processor.py:157} INFO - Started process (PID=9731) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:51:06.735+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:51:06.737+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:51:06.736+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:51:06.766+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:51:06.765+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:51:06.767+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:51:06.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.054 seconds
[2023-08-20T23:51:37.243+0000] {processor.py:157} INFO - Started process (PID=9822) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:51:37.244+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:51:37.245+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:51:37.245+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:51:37.265+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:51:37.264+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:51:37.265+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:51:37.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:52:07.946+0000] {processor.py:157} INFO - Started process (PID=9913) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:52:07.948+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:52:07.949+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:52:07.948+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:52:07.967+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:52:07.966+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:52:07.967+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:52:07.978+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.034 seconds
[2023-08-20T23:52:38.489+0000] {processor.py:157} INFO - Started process (PID=10004) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:52:38.490+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:52:38.491+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:52:38.491+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:52:38.511+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:52:38.510+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:52:38.511+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:52:38.524+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:53:08.790+0000] {processor.py:157} INFO - Started process (PID=10095) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:53:08.791+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:53:08.792+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:53:08.791+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:53:08.811+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:53:08.810+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:53:08.811+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:53:08.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:53:39.070+0000] {processor.py:157} INFO - Started process (PID=10187) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:53:39.071+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:53:39.071+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:53:39.071+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:53:39.093+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:53:39.091+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:53:39.094+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:53:39.108+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.041 seconds
[2023-08-20T23:54:09.508+0000] {processor.py:157} INFO - Started process (PID=10278) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:54:09.510+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:54:09.510+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:54:09.510+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:54:09.532+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:54:09.530+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:54:09.532+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:54:09.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.044 seconds
[2023-08-20T23:54:39.959+0000] {processor.py:157} INFO - Started process (PID=10369) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:54:39.960+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:54:39.961+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:54:39.961+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:54:39.985+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:54:39.984+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:54:39.986+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:54:39.999+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.042 seconds
[2023-08-20T23:55:10.227+0000] {processor.py:157} INFO - Started process (PID=10460) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:55:10.228+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:55:10.230+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:55:10.229+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:55:10.255+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:55:10.253+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:55:10.255+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:55:10.272+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.049 seconds
[2023-08-20T23:55:40.538+0000] {processor.py:157} INFO - Started process (PID=10551) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:55:40.539+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:55:40.540+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:55:40.539+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:55:40.561+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:55:40.560+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:55:40.561+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:55:40.574+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:56:11.486+0000] {processor.py:157} INFO - Started process (PID=10642) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:56:11.487+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:56:11.488+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:56:11.488+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:56:11.508+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:56:11.507+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:56:11.508+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:56:11.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:56:41.874+0000] {processor.py:157} INFO - Started process (PID=10734) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:56:41.875+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:56:41.876+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:56:41.876+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:56:41.896+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:56:41.895+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:56:41.896+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:56:41.909+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
[2023-08-20T23:57:12.627+0000] {processor.py:157} INFO - Started process (PID=10825) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:57:12.628+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:57:12.629+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:57:12.629+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:57:12.650+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:57:12.649+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:57:12.651+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:57:12.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.041 seconds
[2023-08-20T23:57:42.969+0000] {processor.py:157} INFO - Started process (PID=10917) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:57:42.970+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:57:42.971+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:57:42.970+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:57:42.991+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:57:42.990+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:57:42.991+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:57:43.005+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.039 seconds
[2023-08-20T23:58:13.503+0000] {processor.py:157} INFO - Started process (PID=11008) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:58:13.504+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:58:13.505+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:58:13.505+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:58:13.527+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:58:13.525+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:58:13.527+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:58:13.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.040 seconds
[2023-08-20T23:58:44.119+0000] {processor.py:157} INFO - Started process (PID=11099) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:58:44.120+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:58:44.121+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:58:44.121+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:58:44.141+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:58:44.140+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:58:44.142+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:58:44.158+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.041 seconds
[2023-08-20T23:59:14.613+0000] {processor.py:157} INFO - Started process (PID=11190) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:59:14.615+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:59:14.615+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:59:14.615+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:59:14.634+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:59:14.633+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:59:14.635+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:59:14.648+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.037 seconds
[2023-08-20T23:59:45.598+0000] {processor.py:157} INFO - Started process (PID=11281) to work on /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:59:45.599+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/dags_bash_with_variable.py for tasks to queue
[2023-08-20T23:59:45.600+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:59:45.599+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:59:45.619+0000] {logging_mixin.py:150} INFO - [2023-08-20T23:59:45.618+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dags_bash_with_variable.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags_bash_with_variable.py", line 13, in <module>
    var_value = Variable.get("sample_key")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable sample_key does not exist'
[2023-08-20T23:59:45.620+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/dags_bash_with_variable.py
[2023-08-20T23:59:45.633+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dags_bash_with_variable.py took 0.038 seconds
